backend:
  name: github
  repo: neilscheuermann/books-and-buns-v2

media_folder: src/assets/images
public_folder: /images

collections:
  - name: blog
    label: Blog
    folder: src/assets/blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }
